home/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.Home.as_view(), name='home'),

    url(r'^product/(?P<product_id>[0-9]+)/detail/$', views.ProductDetail.as_view(), name='product-detail'),


    url(r'^search/$', views.Search.as_view(), name='search'),
]

investor/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.Home.as_view(), name='home'),


    url(r'^credit/home/$', views.CreditHome.as_view(), name='credit-home'),
    url(r'^credit/recharge/$', views.CreditRecharge.as_view(), name='credit-recharge'),
    url(r'^credit/recharge/pending/$', views.PendingRecharge.as_view(), name='pending-recharge'),
    url(r'^credit/recharge/pending/(?P<credit_recharge_id>[0-9]+)/$', views.PendingRechargeDetail.as_view(), name='pending-recharge-detail'),
]

myfarm/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^', include('home.urls', namespace='home')),

    #staff
    url(r'^staff/', include('staff.urls', namespace='staff')),

    #investor
    url(r'^investor/', include('investor.urls', namespace='investor')),

    #farmer
    url(r'^farmer/', include('farmer.urls', namespace='farmer')),

    #password reset
    url(r'^account/recover-password/$', auth_views.password_reset, {'template_name': 'account/password_reset.html', 'email_template_name': 'account/password_reset_email.html'}, name='password_reset'),
    url(r'^account/recover-password/done/$', auth_views.password_reset_done, {'template_name': 'account/password_reset_done.html'}, name='password_reset_done'),
    url(r'^account/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.password_reset_confirm, {'template_name': 'account/password_reset_confirm.html'},name='password_reset_confirm'),
    url(r'^account/reset/done/$', auth_views.password_reset_complete, {'template_name': 'account/password_reset_complete.html'}, name='password_reset_complete'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

investor/models.py
from django.db import models

# Create your models here.

investor/forms.py
from django import forms

from account import models as account_model


#recharge form
recharge_method_list = (
        ('bkash', 'BKASH'),
        ('dbbl_rocket', 'DBBL/ROCKET'),)

class CreditRechargeForm(forms.Form):
    method = forms.ChoiceField(choices=recharge_method_list, required=False, widget=forms.Select(attrs={'class': 'validate browser-default'}))
    sender_phone_number = forms.CharField(max_length=20, required=False, widget=forms.TextInput(attrs={'class': 'validate', 'id': 'icon_prefix',}))
    transaction_id = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'class': 'validate', 'id': 'icon_prefix',}))
    credit = forms.FloatField(required=False, widget=forms.TextInput(attrs={'class': 'validate'}))


    def clean(self):
        method = self.cleaned_data.get('method')
        sender_phone_number = self.cleaned_data.get('sender_phone_number')
        transaction_id = self.cleaned_data.get('transaction_id')
        credit = self.cleaned_data.get('credit')
        status = self.cleaned_data.get('status')

        if len(sender_phone_number) == 0:
            raise forms.ValidationError('Enter phone number from where you send money!')
        else:
            if len(transaction_id) == 0:
                raise forms.ValidationError('Enter Transaction ID! You found this in the confirmation message in DBBL or BKASH!')
            else:
                if credit == None:
                    raise forms.ValidationError('Enter recharge amount!')



    def deploy(self, request):
        method = self.cleaned_data.get('method')
        sender_phone_number = self.cleaned_data.get('sender_phone_number')
        transaction_id = self.cleaned_data.get('transaction_id')
        credit = self.cleaned_data.get('credit')
        status = self.cleaned_data.get('status')

        deploy = account_model.CreditRecharge(user=request.user, method=method, sender_phone_number=sender_phone_number, transaction_id=transaction_id, credit=credit)

        deploy.save()

investor/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.db.models import Q

from account import models as account_model

from . import forms


#permission mixin
class InvestorPermissionMixin(object):
    def has_permissions(self, request):
        return request.user.investor == True

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            if not self.has_permissions(request):
                return redirect('account:sign-in')
            return super(InvestorPermissionMixin, self).dispatch(
                request, *args, **kwargs)
        else:
            return redirect('account:sign-in')




#investor home
class Home(InvestorPermissionMixin, View):
    template_name = 'investor/index.html'

    def get(self, request):
        change_status_sidebar = 'dashboard'

        variables = {
            'change_status_sidebar': change_status_sidebar,
        }

        return render(request, self.template_name, variables)




#==================================================================================
#==================================================================================
#                                credit
#==================================================================================
#==================================================================================



#credit home
class CreditHome(InvestorPermissionMixin, View):
    template_name = 'investor/credit-home.html'

    def get(self, request):
        change_status_sidebar = 'credit'

        my_wallet = account_model.Credit.objects.get(user=request.user)

        variables = {
            'change_status_sidebar': change_status_sidebar,

            'my_wallet': my_wallet,
        }

        return render(request, self.template_name, variables)



#credit home
class CreditRecharge(InvestorPermissionMixin, View):
    template_name = 'investor/credit-recharge.html'

    def get(self, request):
        change_status_sidebar = 'credit'
        
        recharge_form = forms.CreditRechargeForm()

        variables = {
            'change_status_sidebar': change_status_sidebar,

            'recharge_form': recharge_form,
        }

        return render(request, self.template_name, variables)


    def post(self, request):
        change_status_sidebar = 'credit'

        recharge_form = forms.CreditRechargeForm(request.POST or None)

        if recharge_form.is_valid():
            recharge_form.deploy(request)

        variables = {
            'change_status_sidebar': change_status_sidebar,

            'recharge_form': recharge_form,
        }

        return render(request, self.template_name, variables)




#pending recharge
class PendingRecharge(InvestorPermissionMixin, View):
    template_name = 'investor/pending-recharge.html'

    def get(self, request):
        change_status_sidebar = 'credit'

        pending_recharges = account_model.CreditRecharge.objects.filter(Q(user=request.user) & Q(status='pending'))

        variables = {
            'change_status_sidebar': change_status_sidebar,

            'pending_recharges': pending_recharges,
        }

        return render(request, self.template_name, variables)



#pending recharge
class PendingRechargeDetail(InvestorPermissionMixin, View):
    template_name = 'investor/pending-recharge-detail.html'

    def get(self, request, credit_recharge_id):
        pending_recharge = get_object_or_404(account_model.CreditRecharge, id=credit_recharge_id)

        change_status_sidebar = 'credit'

        variables = {
            'change_status_sidebar': change_status_sidebar,

            'pending_recharge': pending_recharge,
        }

        return render(request, self.template_name, variables)



#==================================================================================
#==================================================================================
#                                credit
#==================================================================================
#==================================================================================

investor/templates/investor/credit-home.html
{% extends 'investor-base.html' %}

{% block title %} MyFarm | Investor {% endblock %}


{% block body %}
    <div class="col m10 offset-m1" style="padding: 20px; margin-top: 20px; margin-bottom: 20px;">
        <h5>Credit: {{ my_wallet.credit }} BDT</h5>

        <p class="col s12 m12 l12 divider">

        </p>

        <a href="{% url 'investor:credit-recharge' %}" class="btn waves-effect waves-light black" style="margin-top: 30px;">
            Recharge Credit
        </a>

        <a href="{% url 'investor:pending-recharge' %}" class="btn waves-effect waves-light black" style="margin-top: 30px;">
            Pending Recharge
        </a>

        <a class="btn waves-effect waves-light black" style="margin-top: 30px;">
            Recharge History
        </a>
        <br>

        <a class="btn waves-effect waves-light black" style="margin-top: 30px;">
            Transaction History
        </a>

    </div>
{% endblock %}

investor/templates/investor/credit-recharge.html
{% extends 'investor-base.html' %}

{% block title %} MyFarm | Investor {% endblock %}


{% block body %}
    <div class="col m10 offset-m1" style="padding: 20px; margin-top: 20px; margin-bottom: 20px;">
        <h5>Credit Recharge</h5>

        <p class="col s12 m12 l12 divider">

        </p>

        <div class="col s12 m12 l12" style="margin-top: 10px;">
            <div class="card blue">
                <div class="card-content white-text">
                    <span class="card-title">Recharge From BKASH</span>
                    <p>
                        Our BKASH number is : 01XXXXXXXXX.<br>
                        You need to send money to this BKASH number from your BKASH number. Then BKASH
                        gives you unique TRANSACTION ID. With That TRANSACTION ID and your BKASH number ,just fill the
                         form correctly. We AUTHORIZE your transaction amount and credited to your account.
                    </p>
                </div>

                <div class="divider white">

                </div>

                <div class="card-content white-text">
                    <span class="card-title">Recharge From DBBL/ROCKET</span>
                    <p>
                        Our DBBL/ROCKET number is : 01XXXXXXXXXX.<br>
                        You need to send money to this DBBL/ROCKET number from your DBBL/ROCKET number. Then DBBL/ROCKET
                        gives you unique TRANSACTION ID. With That TRANSACTION ID and your DBBL/ROCKET number ,just fill the
                         form correctly. We AUTHORIZE your transaction amount and credited to your account.
                    </p>
                </div>
            </div>
        </div>


        <form class="col s12 m10 offset-m1 l10 offset-l1" method="post" style="margin-top: 50px; margin-bottom: 50px;">
            {% csrf_token %}

            <div class="col s12 m12 l12">
                <label>Payment Method</label>
                {{ recharge_form.method }}
            </div>

            <div class="input-field col s12 m12 l12" style="margin-top: 20px;">
                <i class="material-icons prefix">phone</i>
                {{ recharge_form.sender_phone_number }}
                <label for="icon_prefix white-text">Sender Phone Number</label>
            </div>

            <div class="input-field col s12 m12 l12" style="margin-top: 20px;">
                <i class="material-icons prefix">equalizer</i>
                {{ recharge_form.transaction_id }}
                <label for="icon_prefix white-text">Transaction ID</label>
            </div>


            <div class="input-field col s12 m12 l12">
                <i class="material-icons prefix">attach_money</i>
                {{ recharge_form.credit }}
                <label for="icon_prefix white-text">Credit Amount</label>
            </div>

            {% if recharge_form.non_field_errors %}
                {% for error in recharge_form.non_field_errors %}
                    <div class="col s12 m10 offset-m1 l10 offset-l1 valign-wrapper" style="margin-top: 20px; background-color: red; height: 40px;">
                        <p style="color: white; font-size: 16px;">
                            {{ error }}
                        </p>
                    </div>
                {% endfor %}
            {% endif %}

            <div class="col s12 m12 l12" style="margin-bottom: 20px; margin-top: 20px;">
                <button class="btn waves-effect waves-light black" type="submit" style="">Recharge
                    <i class="material-icons right">send</i>
                </button>
            </div>
        </form>

    </div>
{% endblock %}

investor/templates/investor/index.html
{% extends 'investor-base.html' %}

{% block title %} MyFarm | Investor {% endblock %}


{% block body %}
    <div class="col m10 offset-m1" style="padding: 20px; margin-top: 20px; margin-bottom: 20px;">
        <h5>Investor Dashboard</h5>

        <p class="col s12 m12 l12 divider">

        </p>

    </div>
{% endblock %}

investor/templates/investor/pending-recharge-detail.html
{% extends 'investor-base.html' %}

{% block title %} MyFarm | Investor {% endblock %}


{% block body %}
    <div class="col m10 offset-m1" style="padding: 20px; margin-top: 20px; margin-bottom: 20px;">
        <h5>Pending Recharge Detail</h5>

        <p class="col s12 m12 l12 divider">

        </p>

        <div class="col s12 m12 l12" style="margin-top: 20px;">
            <p>Recharge Date: {{  pending_recharge.date }}</p>

            <p>Payment Method :
                {% if pending_recharge.method == 'bkash' %}
                BKASH
                {% endif %}

                {% if pending_recharge.method == 'dbbl_rocket' %}
                DBBL/ROCKET
                {% endif %}
            </p>

            <p>Sender Phone Number: {{ pending_recharge.sender_phone_number }}</p>
            <p>Transaction ID: {{ pending_recharge.transaction_id }}</p>
            <p>Credit Amount: {{ pending_recharge.credit }} BDT</p>

            {% if pending_recharge.status == 'pending' %}
                <p>Payment Status: <span style="color: red;">{{ pending_recharge.status | title }}</span></p>
            {% else %}
                <p>Payment Status: <span style="color: green;">{{ pending_recharge.status | title }}</span></p>
            {% endif %}
        </div>

    </div>
{% endblock %}

investor/templates/investor/pending-recharge.html
{% extends 'investor-base.html' %}

{% block title %} MyFarm | Investor {% endblock %}


{% block body %}
    <div class="col m10 offset-m1" style="padding: 20px; margin-top: 20px; margin-bottom: 20px;">
        <h5>Pending Recharge List</h5>

        <p class="col s12 m12 l12 divider">

        </p>

        <div class="col s12 m12 l12" style="margin-top: 20px;">
            <table class="highlight centered responsive-table">
                <thead>
                    <tr>
                        <th>S/N</th>
                        <th>Date</th>
                        <th>Payment Method</th>
                        <th>Amount</th>
                        <th>Status</th>
                        <th>Operation</th>
                    </tr>
                </thead>

                <tbody class="table_data">
                    {% for pending_recharge in pending_recharges %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ pending_recharge.date }}</td>

                        <td>
                            {% if pending_recharge.method == 'bkash' %}
                                BKASH
                            {% endif %}

                            {% if pending_recharge.method == 'dbbl_rocket' %}
                                DBBL/ROCKET
                            {% endif %}
                        </td>

                        <td>{{ pending_recharge.credit }}</td>

                        <td>
                            {{ pending_recharge.status }}
                        </td>

                        <td>
                            <a href="{% url 'investor:pending-recharge-detail' credit_recharge_id=pending_recharge.id %}">View</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

    </div>
{% endblock %}