account/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^sign-out/$', views.signout_request, name='sign-out'),
    url(r'^sign-up/$', views.SignUp.as_view(), name='sign-up'),
    url(r'^sign-in/$', views.SignIn.as_view(), name='sign-in'),

    url(r'^profile/$', views.Profile.as_view(), name='profile'),
    url(r'^profile/edit/$', views.ProfileEdit.as_view(), name='profile-edit'),
    url(r'^change-password/$', views.ChangePassword.as_view(), name='change-password'),

    #api
    url(r'^api/user-profile/$', views.UserProfileAPI.as_view(), name='user-profile-api'),
]

backup/staff/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.Home.as_view(), name='home'),

    url(r'^user/all/$', views.AllUser.as_view(), name='all-user'),
    url(r'^user/detail/(?P<user_id>[0-9]+)/$', views.UserDetail.as_view(), name='user-detail'),

    url(r'^user/(?P<profile_status>[a-zA-z]+)/(?P<user_id>[0-9]+)/$', views.ActiveDeactiveUser.as_view(), name='active-deactive-user'),
    url(r'^user/(?P<user_id>[0-9]+)/delete/$', views.DeleteUser.as_view(), name='delete-user'),
    url(r'^user/(?P<user_id>[0-9]+)/change-password/$', views.ChangeUserPassword.as_view(), name='change-user-password'),

    url(r'^user/(?P<user_id>[0-9]+)/edit/$', views.EditUser.as_view(), name='edit-user'),


    #product block start

    url(r'^product/add/$', views.ProductAdd.as_view(), name='product-add'),

    #product block end

]

home/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.Home.as_view(), name='home'),

    url(r'^product/(?P<product_id>[0-9]+)/detail/$', views.ProductDetail.as_view(), name='product-detail'),


    url(r'^search/$', views.Search.as_view(), name='search'),
]

myfarm/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^account/', include('account.urls', namespace='account')),
    url(r'^', include('home.urls', namespace='home')),

    #staff
    url(r'^staff/', include('staff.urls', namespace='staff')),

    #investor
    url(r'^investor/', include('investor.urls', namespace='investor')),

    #farmer
    url(r'^farmer/', include('farmer.urls', namespace='farmer')),

    #password reset
    url(r'^account/recover-password/$', auth_views.password_reset, {'template_name': 'account/password_reset.html', 'email_template_name': 'account/password_reset_email.html'}, name='password_reset'),
    url(r'^account/recover-password/done/$', auth_views.password_reset_done, {'template_name': 'account/password_reset_done.html'}, name='password_reset_done'),
    url(r'^account/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.password_reset_confirm, {'template_name': 'account/password_reset_confirm.html'},name='password_reset_confirm'),
    url(r'^account/reset/done/$', auth_views.password_reset_complete, {'template_name': 'account/password_reset_complete.html'}, name='password_reset_complete'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

staff/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.Home.as_view(), name='home'),

    #user management url
    url(r'^user/home/$', views.UserHome.as_view(), name='user-home'),
    url(r'^user/all/$', views.AllUser.as_view(), name='all-user'),
    url(r'^user/detail/(?P<user_id>[0-9]+)/$', views.UserDetail.as_view(), name='user-detail'),

    url(r'^user/(?P<profile_status>[a-zA-z]+)/(?P<user_id>[0-9]+)/$', views.ActiveDeactiveUser.as_view(), name='active-deactive-user'),
    url(r'^user/(?P<user_id>[0-9]+)/delete/$', views.DeleteUser.as_view(), name='delete-user'),
    url(r'^user/(?P<user_id>[0-9]+)/change-password/$', views.ChangeUserPassword.as_view(), name='change-user-password'),

    url(r'^user/(?P<user_id>[0-9]+)/edit/$', views.EditUser.as_view(), name='edit-user'),


    #product block start
    url(r'^product/home/$', views.ProductHome.as_view(), name='product-home'),
    url(r'^product/add/$', views.ProductAdd.as_view(), name='product-add'),

    #product block end

    #payment block start
    url(r'^payment/home/$', views.PaymentHome.as_view(), name='payment-home'),
    url(r'^payment/pending/recharge/$', views.PaymentPendingRecharge.as_view(), name='payment-pending-recharge'),
    url(r'^payment/pending/recharge//$', views.PaymentPendingRecharge.as_view(), name='payment-pending-recharge'),
    url(r'^payment/recharge/pending/(?P<credit_recharge_id>[0-9]+)/$', views.PendingRechargeDetail.as_view(), name='payment-pending-recharge-detail'),
    #url(r'^product/add/$', views.ProductAdd.as_view(), name='product-add'),

    #payment block end

]

backup/staff/forms.py
from django import forms
from django.contrib.auth.hashers import make_password, check_password

from account import models as account_model
from . import models

#change user password from staff
class ChangeUserPasswordForm(forms.Form):
    new_password1 = forms.CharField(max_length=20, required=False, widget=forms.PasswordInput(attrs={'class': 'validate'}))
    new_password2 = forms.CharField(max_length=20, required=False, widget=forms.PasswordInput(attrs={'class': 'validate'}))

    def clean(self):
        new_password1 = self.cleaned_data.get('new_password1')
        new_password2 = self.cleaned_data.get('new_password2')

        if len(new_password1) < 8:
            raise forms.ValidationError("Password is too short!")
        else:
            if new_password1 != new_password2:
                raise forms.ValidationError("Password not matched!")


    def deploy(self, user_id):
        new_password1 = self.cleaned_data.get('new_password1')
        new_password2 = self.cleaned_data.get('new_password2')

        hash_pass = make_password(new_password1)

        deploy = account_model.UserProfile.objects.filter(id=user_id).update(password=hash_pass)



#product form
class ProductForm(forms.Form):
    name = forms.CharField(max_length=255, required=False, widget=forms.TextInput(attrs={'class': 'validate'}))
    contact_period = forms.FloatField(required=False, widget=forms.TextInput(attrs={'class': 'validate'}))
    expected_return = forms.FloatField(required=False, widget=forms.TextInput(attrs={'class': 'validate'}))
    harvest_period = forms.FloatField(required=False, widget=forms.TextInput(attrs={'class': 'validate'}))

    title = forms.CharField(max_length=255, required=False, widget=forms.TextInput(attrs={'class': 'validate'}))
    description = forms.CharField(required=False, max_length=10000, widget=forms.Textarea(attrs={'class': 'validate materialize-textarea'}))
    extra = forms.CharField(required=False, max_length=5000, widget=forms.Textarea(attrs={'class': 'validate materialize-textarea'}))

    farm_size = forms.FloatField(required=False, widget=forms.TextInput(attrs={'class': 'validate'}))
    price = forms.FloatField(required=False, widget=forms.TextInput(attrs={'class': 'validate'}))
    farm_location = forms.CharField(required=False, max_length=5000, widget=forms.Textarea(attrs={'class': 'validate materialize-textarea'}))

    product_type = forms.CharField(max_length=255, required=False, widget=forms.TextInput(attrs={'class': 'validate'}))
    farm_email = forms.EmailField(max_length=255, required=False, widget=forms.TextInput(attrs={'class': 'validate'}))
    product_image = forms.ImageField(required=False)


    def clean(self):
        name = self.cleaned_data.get('name')
        contact_period = self.cleaned_data.get('contact_period')
        expected_return = self.cleaned_data.get('expected_return')
        harvest_period = self.cleaned_data.get('harvest_period')
        title = self.cleaned_data.get('title')
        description = self.cleaned_data.get('description')
        extra = self.cleaned_data.get('extra')
        farm_size = self.cleaned_data.get('farm_size')
        farm_location = self.cleaned_data.get('farm_location')
        product_type = self.cleaned_data.get('product_type')
        farm_email = self.cleaned_data.get('farm_email')
        product_image = self.cleaned_data.get('product_image')
        price = self.cleaned_data.get('price')


        if name == None:
            raise forms.ValidationError('Enter product name!')
        else:
            if contact_period == None:
                raise forms.ValidationError('Enter contact period!')
            else:
                if expected_return == None:
                    raise forms.ValidationError('Enter expected return in %!')
                else:
                    if harvest_period == None:
                        raise forms.ValidationError('Enter harvest period in month!')
                    else:
                        if title == None:
                            raise forms.ValidationError('Enter product title!')
                        else:
                            if description == None:
                                raise forms.ValidationError('Enter product description!')
                            else:
                                if product_image == None:
                                    raise forms.ValidationError('Select product image!')
                                else:
                                    if price == None:
                                        raise forms.ValidationError('Enter product price!')




    def deploy(self, request):
        name = self.cleaned_data.get('name')
        contact_period = self.cleaned_data.get('contact_period')
        expected_return = self.cleaned_data.get('expected_return')
        harvest_period = self.cleaned_data.get('harvest_period')
        title = self.cleaned_data.get('title')
        description = self.cleaned_data.get('description')
        extra = self.cleaned_data.get('extra')
        farm_size = self.cleaned_data.get('farm_size')
        farm_location = self.cleaned_data.get('farm_location')
        product_type = self.cleaned_data.get('product_type')
        farm_email = self.cleaned_data.get('farm_email')
        product_image = self.cleaned_data.get('product_image')
        price = self.cleaned_data.get('price')


        deploy = models.Product(user=request.user, name=name, contact_period=contact_period, expected_return=expected_return, harvest_period=harvest_period, price=price, title=title, description=description, extra=extra, farm_size=farm_size, farm_location=farm_location, product_type=product_type, farm_email=farm_email, product_image=product_image)
        deploy.save()

backup/staff/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View

from account import models as account_model
from account import forms as account_form

from . import forms
from . import models


#permission mixin
class StaffPermissionMixin(object):
    def has_permissions(self, request):
        return request.user.is_staff == True or request.user.is_superuser == True

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            if not self.has_permissions(request):
                return redirect('account:sign-in')
            return super(StaffPermissionMixin, self).dispatch(
                request, *args, **kwargs)
        else:
            return redirect('account:sign-in')



#staff home
class Home(StaffPermissionMixin, View):
    template_name = 'staff/index.html'

    def get(self, request):

        variables = {

        }

        return render(request, self.template_name, variables)

    def post(self, request):
        pass



#all user
class AllUser(StaffPermissionMixin, View):
    template_name = 'staff/all-user.html'

    def get(self, request):

        all_users = account_model.UserProfile.objects.all()
        all_users_count = account_model.UserProfile.objects.all().count()

        variables = {
            'all_users': all_users,
            'all_users_count': all_users_count,
        }

        return render(request, self.template_name, variables)

    def post(self, request):
        pass



#user detail
class UserDetail(StaffPermissionMixin, View):
    template_name = 'staff/user-detail.html'

    def get(self, request, user_id):

        get_object_or_404(account_model.UserProfile, pk=user_id)
        users = account_model.UserProfile.objects.filter(id=user_id)

        variables = {
            'users': users,
        }

        return render(request, self.template_name, variables)

    def post(self, request, user_id):
        pass


#active or deactive user
class ActiveDeactiveUser(StaffPermissionMixin, View):
    template_name = 'staff/active-deactive-user.html'

    def get(self, request, profile_status, user_id):

        get_object_or_404(account_model.UserProfile, pk=user_id)
        users = account_model.UserProfile.objects.filter(id=user_id)

        variables = {
            'users': users,
            'profile_status': profile_status,
        }

        return render(request, self.template_name, variables)

    def post(self, request, profile_status, user_id):
        get_object_or_404(account_model.UserProfile, pk=user_id)
        users = account_model.UserProfile.objects.filter(id=user_id)

        if request.POST.get('yes') == 'yes':
            for user in users:
                if profile_status == 'activate':
                    user.is_active = True
                    user.save()
                elif profile_status == 'deactivate':
                    user.is_active = False
                    user.save()
            return redirect('staff:user-detail', user_id=user_id)

        elif request.POST.get('no') == 'no':
            return redirect('staff:user-detail', user_id=user_id)


        variables = {
            'users': users,
            'profile_status': profile_status,
        }

        return render(request, self.template_name, variables)




#delete user
class DeleteUser(StaffPermissionMixin, View):
    template_name = 'staff/delete-user.html'

    def get(self, request, user_id):

        get_object_or_404(account_model.UserProfile, pk=user_id)
        users = account_model.UserProfile.objects.filter(id=user_id)

        variables = {
            'users': users,
        }

        return render(request, self.template_name, variables)

    def post(self, request, user_id):
        get_object_or_404(account_model.UserProfile, pk=user_id)
        users = account_model.UserProfile.objects.filter(id=user_id)

        if request.POST.get('yes') == 'yes':
            users.delete()
            return redirect('staff:all-user')

        elif request.POST.get('no') == 'no':
            return redirect('staff:all-user')

        variables = {
            'users': users,
        }

        return render(request, self.template_name, variables)



#edit user
class EditUser(StaffPermissionMixin, View):
    template_name = 'staff/user-edit.html'

    def get(self, request, user_id):

        get_object_or_404(account_model.UserProfile, pk=user_id)
        users = account_model.UserProfile.objects.filter(id=user_id)

        profile_edit_form = account_form.ProfileEditForm(instance=account_model.UserProfile.objects.get(id=user_id))

        variables = {
            'users': users,
            'profile_edit_form': profile_edit_form,
        }

        return render(request, self.template_name, variables)

    def post(self, request, user_id):
        get_object_or_404(account_model.UserProfile, pk=user_id)
        users = account_model.UserProfile.objects.filter(id=user_id)

        profile_edit_form = account_form.ProfileEditForm(request.POST or None, instance=account_model.UserProfile.objects.get(id=user_id))

        if profile_edit_form.is_valid():
            profile_edit_form.save()

        variables = {
            'users': users,
            'profile_edit_form': profile_edit_form,
        }

        return render(request, self.template_name, variables)



#change user password
class ChangeUserPassword(View):
    template_name = 'staff/change-user-password.html'

    def get(self, request, user_id):

        get_object_or_404(account_model.UserProfile, pk=user_id)
        users = account_model.UserProfile.objects.filter(id=user_id)

        change_user_password = forms.ChangeUserPasswordForm()

        variables = {
            'users': users,
            'change_user_password': change_user_password,
        }

        return render(request, self.template_name, variables)

    def post(self, request, user_id):
        get_object_or_404(account_model.UserProfile, pk=user_id)
        users = account_model.UserProfile.objects.filter(id=user_id)

        change_user_password = forms.ChangeUserPasswordForm(request.POST or None)

        if change_user_password.is_valid():
            change_user_password.deploy(user_id)

        variables = {
            'users': users,
            'change_user_password': change_user_password,
        }

        return render(request, self.template_name, variables)



#staff home
class ProductAdd(StaffPermissionMixin, View):
    template_name = 'staff/product-add.html'

    def get(self, request):

        add_product_form = forms.ProductForm()

        variables = {
            'add_product_form': add_product_form,
        }

        return render(request, self.template_name, variables)

    def post(self, request):
        add_product_form = forms.ProductForm(request.POST or None, request.FILES)

        if add_product_form.is_valid():
            add_product_form.deploy(request)

        variables = {
            'add_product_form': add_product_form,
        }

        return render(request, self.template_name, variables)

staff/templates/staff/all-user.html
{% extends 'staff-base.html' %}

{% block title %} MyFarm | Staff {% endblock %}

{% block style %}
    <style>
        .table_data a:hover{
            text-decoration: underline;
        }
    </style>
{% endblock %}

{% block body %}
    <!--user table-->
    <div class="col s12 m12 l12" style="">
        <table class="highlight centered responsive-table">
            <thead>
                <tr>
                    <th>S/N</th>
                    <th>Username</th>
                    <th>Email</th>
                    <th>Profile</th>
                    <th>Operation</th>
                </tr>
            </thead>

            <tbody class="table_data">
                {% for all_user in all_users %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ all_user.username | title }}</td>
                    <td>{{ all_user.email }}</td>

                    <td>
                        {% if all_user.is_active %}
                            <span style="color: green;">Active</span>
                        {% else %}
                            <span style="color: red;">Deactive</span>
                        {% endif %}
                    </td>

                    <td>
                        <a href="{% url 'staff:user-detail' user_id=all_user.id %}">View</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <!--end user table-->
{% endblock %}

staff/templates/staff/index.html
{% extends 'staff-base.html' %}

{% block title %} MyFarm | Staff {% endblock %}


{% block body %}
    <div class="col m8 offset-m2" style="padding: 20px; margin-top: 20px; margin-bottom: 20px;">
        <h5>Quick Link</h5>

        <p class="col s12 m12 l12 divider">

        </p>

        <a href="{% url 'staff:user-home' %}" class="waves-effect waves-light btn red white-text" style="margin-top: 20px;">User Management</a>
        <a href="{% url 'staff:product-home' %}" class="waves-effect waves-light btn red white-text" style="margin-top: 20px;">Product Management</a>
    </div>
{% endblock %}

staff/templates/staff/payment-home.html
{% extends 'staff-base.html' %}

{% block title %} MyFarm | Staff {% endblock %}


{% block body %}
    <div class="col m10 offset-m1" style="padding: 20px; margin-top: 20px; margin-bottom: 20px;">
        <h5>Payment Dashboard</h5>

        <p class="col s12 m12 l12 divider">

        </p>

        <a href="{% url 'staff:payment-pending-recharge' %}" class="btn waves-effect waves-light black" style="margin-top: 30px;">
            Pending Recharge
        </a>

        <a class="btn waves-effect waves-light black" style="margin-top: 30px;">
            Recharge History
        </a>
        <br>

    </div>
{% endblock %}

staff/templates/staff/payment-pending-recharge.html
{% extends 'staff-base.html' %}

{% block title %} MyFarm | Investor {% endblock %}


{% block body %}
    <div class="col m10 offset-m1" style="padding: 20px; margin-top: 20px; margin-bottom: 20px;">
        <h5>Pending Recharge List</h5>

        <p class="col s12 m12 l12 divider">

        </p>

        <div class="col s12 m12 l12" style="margin-top: 20px;">
            <table class="highlight centered responsive-table">
                <thead>
                    <tr>
                        <th>S/N</th>
                        <th>Username</th>
                        <th>Date</th>
                        <th>Payment Method</th>
                        <th>Amount</th>
                        <th>Status</th>
                        <th>Operation</th>
                    </tr>
                </thead>

                <tbody class="table_data">
                    {% for pending_recharge in pending_recharges %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ pending_recharge.user.username | title }}</td>
                        <td>{{ pending_recharge.date }}</td>

                        <td>
                            {% if pending_recharge.method == 'bkash' %}
                                BKASH
                            {% endif %}

                            {% if pending_recharge.method == 'dbbl_rocket' %}
                                DBBL/ROCKET
                            {% endif %}
                        </td>

                        <td>{{ pending_recharge.credit }}</td>

                        <td>
                            {{ pending_recharge.status }}
                        </td>

                        <td>
                            <a href="{% url 'staff:payment-pending-recharge-detail' credit_recharge_id=pending_recharge.id %}">View</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

    </div>
{% endblock %}

staff/templates/staff/product-home.html
{% extends 'staff-base.html' %}

{% block title %} MyFarm | Staff {% endblock %}


{% block body %}
    <div class="col m8 offset-m2" style="padding: 20px; margin-top: 20px; margin-bottom: 20px;">

        <h5 style="margin-top: 50px;">Post Product</h5>

        <p class="col s12 m12 l12 divider">

        </p>

        <a href="{% url 'staff:product-add' %}" class="waves-effect waves-light btn red white-text" style="margin-top: 20px;">Add Product</a>
        <a href="{% url 'account:sign-out' %}" class="waves-effect waves-light btn red white-text" style="margin-top: 20px;">Search user</a>
    </div>
{% endblock %}

staff/templates/staff/user-detail.html
{% extends 'staff-base.html' %}

{% block title %} MyFarm | Staff {% endblock %}


{% block body %}
    {% if users %}
        {% for user in users %}
        <div class="col s12 m8 offset-m2 l8 offset-l2" style="">
            <div class="col s12 m12 l12" style="margin-top: 40px;">
                <div class="col m2">
                    {% if user.photo %}
                    <img src="{{ request.user.photo.url }}" width="100%" height="100%">
                    {% else %}
                    <img src="/media/no-img.jpg" width="100%" height="100%">
                    {% endif %}
                </div>

                <div class="col m8" style="">
                    <p style="font-size: 18px;">{{ user.username | title }}</p>
                    <p style="font-size: 14px;">@mail : {{ user.email }}</p>

                    {% if request.user.phone %}
                        <p style="font-size: 14px;">@call : {{ user.phone }}</p>
                    {% endif %}

                    {% if user.is_staff or user.is_superuser %}
                        <p style="font-size: 14px;">@status : <span style="color: blue;">Staff</span></p>
                    {% endif %}

                    {% if user.is_active %}
                        <p style="font-size: 14px;">@profile : <span style="color: green;">Active</span></p>
                    {% else %}
                        <p style="font-size: 14px;">@profile : <span style="color: red;">Deactive</span></p>
                    {% endif %}
                </div>
            </div>

            <div class="col s12 m12 l12" style="margin-bottom: 50px; margin-top: 40px;">
                <p class="left" style="font-size: 22px;">Basic Information</p>

                <a href="{% url 'staff:edit-user' user_id=user.id %}" class="right" style="font-size: 14px;">edit profile</a>
                <p class="col s12 m12 l12 divider" style="margin-top: 5px;"></p>

                <div class="col s12 m12 l12" style="padding: 10px; margin-top: 5px;">
                    <p>Username : {{ user.username | title }}</p>
                    <p>Email : {{ user.email }}</p>
                    {% if user.phone %}
                        <p>Phone : {{ user.phone }}</p>
                    {% endif %}

                    <a href="{% url 'staff:change-user-password' user_id=user.id %}" class="waves-effect waves-light btn green white-text" style="margin-top: 20px;">Change password</a>

                    <br>

                    {% if user.is_active %}
                        <a href="{% url 'staff:active-deactive-user' profile_status='deactivate' user_id=user.id %}" class="waves-effect waves-light btn red white-text" style="margin-top: 20px;">Deactivate This Account</a><br>
                    {% else %}
                        <a href="{% url 'staff:active-deactive-user' profile_status='activate' user_id=user.id %}" class="waves-effect waves-light btn red white-text" style="margin-top: 20px;">Activate This Account</a><br>
                    {% endif %}


                    {% if user.job_title or user.company or user.address or user.suit_floor_apt or user.city or user.state or user.zip_postal_code or user.country %}
                        <p class="col s12 m12 l12 divider" style="margin-top: 20px; margin-bottom: 10px;"></p>
                    {% endif %}

                    {% if user.job_title %}
                        <p>Job title : {{ user.job_title | title }}</p>
                    {% endif %}

                    {% if user.company %}
                        <p>Company : {{ user.company | title }}</p>
                    {% endif %}

                    {% if user.address %}
                        <p>Address : {{ user.address }}</p>
                    {% endif %}

                    {% if user.suit_floor_apt %}
                        <p>Suit floor / apartment : {{ user.suit_floor_apt }}</p>
                    {% endif %}

                    {% if user.city %}
                        <p>City : {{ user.city | title }}</p>
                    {% endif %}

                    {% if user.state %}
                        <p>State : {{ user.state }}</p>
                    {% endif %}

                    {% if user.zip_postal_code %}
                        <p>Zip / postal code : {{ user.zip_postal_code }}</p>
                    {% endif %}

                    {% if user.country %}
                        <p>Country : {{ user.country }}</p>
                    {% endif %}

                    {% if user.is_active or user.is_staff or user.is_superuser %}
                        <p class="col s12 m12 l12 divider" style="margin-top: 20px; margin-bottom: 10px;"></p>
                    {% endif %}

                    {% if user.is_staff or user.is_superuser %}
                        <p style="font-size: 14px;">Status : <span style="color: blue;">Staff</span></p>
                    {% endif %}

                    {% if user.is_active %}
                        <p style="font-size: 14px;">Profile : <span style="color: green;">Active</span></p>
                    {% else %}
                        <p style="font-size: 14px;">Profile : <span style="color: red;">Deactive</span></p>
                    {% endif %}

                    <a href="{% url 'staff:delete-user' user_id=user.id %}" class="waves-effect waves-light btn red white-text" style="margin-top: 20px;">Delete This Account</a>

                </div>
            </div>
        </div>
        {% endfor %}
    {% else %}
        <h5>No user found!</h5>
    {% endif %}
    <!--end sign up form-->

{% endblock %}

staff/templates/staff/user-home.html
{% extends 'staff-base.html' %}

{% block title %} MyFarm | Staff {% endblock %}


{% block body %}
    <div class="col m8 offset-m2" style="padding: 20px; margin-top: 20px; margin-bottom: 20px;">
        <h5>User management</h5>

        <p class="col s12 m12 l12 divider">

        </p>

        <a href="{% url 'staff:all-user' %}" class="waves-effect waves-light btn red white-text" style="margin-top: 20px;">All user</a>
        <a href="{% url 'account:sign-out' %}" class="waves-effect waves-light btn red white-text" style="margin-top: 20px;">Search user</a>


    </div>
{% endblock %}